repos:
  - repo: https://github.com/mwouts/jupytext
    rev: v1.16.7
    hooks:
    - id: jupytext
      args: [--from, ipynb, --to, ipynb, --update-metadata, '{"kernelspec": {"display_name": "SEP Tools", "language": "python", "name": "python3"}}']
